### ISSUE TITLE
add depends_on to docker-compose.yml example

### ISSUE THREAD

**Issue by globus243** [fhem/alexa-fhem-docker#96]
I noticed that fhem is often slower than alexa-fhem, which leads to errors in the log, adding depends_on to the alexa-fhem part in the compose would mitigate this:

```
version: '2.3'

networks:
  fhem_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/28
          gateway: 172.27.0.1
        - subnet: fd00:0:0:0:27::/80
          gateway: fd00:0:0:0:27::1


services:
  # Minimum example w/o any custom environment variables of fhem container
  fhem:
    image: ghcr.io/fhem/fhem/fhem-docker:bullseye
    restart: always
    networks:
      - fhem_net
    ports:
      - "8083:8083"
    volumes:
      - "./fhem/:/opt/fhem/"

 # Minimum example w/o any custom environment variables of alexa-fhem container
 alexa-fhem:
    image: ghcr.io/fhem/fhem/alexa-fhem:v4.0.3
    restart: always
    depends_on: # <--- wait for fhem to start and return a good healthcheck
      - fhem
    networks:
     - fhem_net
    ports:
      - "3000:3000"
    volumes:
      - "./alexa-fhem/:/alexa-fhem/"
    environment:
      ALEXAFHEM_UID: 6062
      ALEXAFHEM_GID: 6062
      TZ: Europe/Berlin
```

**Comment by sidey79** [comment]
I have a running config exactly the oppsosit way

my fhem container depends on alexa-fhem container
What is the issue if alexa-fhem is running before FHEM?

```
  fhem:
    image:  ghcr.io/fhem/fhem/fhem-minimal-docker:3.1.6-bullseye
    restart: always
    networks:
      - fhem_net
    depends_on: 
      - "db"
      - "alexa-fhem"
```

**Comment by globus243** [comment]
Since Alexa-fhem starts much quicker than fhem, it produces errors in its log during the first few seconds, or however long fhem takes to become responsive. However, this has no impact other than generating some error logs. Even with the 'depends_on' condition, fhem starts to return a green health check a few seconds before it begins responding to the Alexa-fhem requests. Therefore, there are still one or two errors, but notably fewer than without the 'depends_on' condition, at least that's what I noticed on my end. 

> my fhem container depends on alexa-fhem container

Correct me if I am wrong, but logically, the Alexa-fhem component relies on fhem being up and running. Since depends_on ensures that the depending container is up before the other container starts, doesn't it make more sense to have Alexa-fhem depend on fhem?

so my productive compose is like this:

````
version: '2.1'

services:
  fhem:
    image: xxxxxx.dkr.ecr.eu-central-1.amazonaws.com/fhem:latest
    container_name: fhem-stateless
    restart: always
    ports:
      - "8080:8083"
    networks:
      - fhem_net
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  alexa-fhem:
    image: xxxxxx.dkr.ecr.eu-central-1.amazonaws.com/fhem-alexa:latest
    container_name: fhem-alexa
    depends_on:
      - fhem
    restart: always
    networks:
      - fhem_net
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  gassistant-fhem:
    image: xxxxxx.dkr.ecr.eu-central-1.amazonaws.com/fhem-gassistant:latest
    container_name: fhem-gassistant
    depends_on:
      - fhem
    restart: always
    networks:
        - fhem_net
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

networks:
  fhem_net:
    driver: bridge
````
